In [82]:
import yfinance as yf
import pandas as pd
import numpy as np

In [83]:
ticker = yf.Ticker("B3SA3.SA")
stock = ticker.actions
stock

Dividends  Stock Splits
Date                                              
2008-08-26 00:00:00-03:00   0.024332           0.0
2009-01-02 00:00:00-02:00   0.023102           0.0
2009-05-04 00:00:00-03:00   0.020682           0.0
2009-05-18 00:00:00-03:00   0.018644           0.0
2009-08-17 00:00:00-03:00   0.020019           0.0
...                              ...           ...
2023-09-29 00:00:00-03:00   0.105230           0.0
2024-01-02 00:00:00-03:00   0.100519           0.0
2024-02-28 00:00:00-03:00   0.066900           0.0
2024-03-27 00:00:00-03:00   0.052453           0.0
2024-06-19 00:00:00-03:00   0.086087           0.0

[79 rows x 2 columns]

In [84]:
stock_split = stock["Stock Splits"].to_numpy()
stock_split

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
stock_split_replaced = np.where(stock_split == 0, 1, stock_split)
stock_split_replaced

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 3., 3., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
stock_split_comp = np.cumprod(stock_split_replaced, axis=0)
stock_split_comp

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 3., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [87]:
stock["stocksplit_adj"] = stock_split_comp.tolist()
stock

Dividends  Stock Splits  stocksplit_adj
Date                                                              
2008-08-26 00:00:00-03:00   0.024332           0.0             1.0
2009-01-02 00:00:00-02:00   0.023102           0.0             1.0
2009-05-04 00:00:00-03:00   0.020682           0.0             1.0
2009-05-18 00:00:00-03:00   0.018644           0.0             1.0
2009-08-17 00:00:00-03:00   0.020019           0.0             1.0
...                              ...           ...             ...
2023-09-29 00:00:00-03:00   0.105230           0.0             9.0
2024-01-02 00:00:00-03:00   0.100519           0.0             9.0
2024-02-28 00:00:00-03:00   0.066900           0.0             9.0
2024-03-27 00:00:00-03:00   0.052453           0.0             9.0
2024-06-19 00:00:00-03:00   0.086087           0.0             9.0

[79 rows x 3 columns]

In [88]:
stock["div_adj"] = stock["Dividends"] * stock["stocksplit_adj"]
stock

Dividends  Stock Splits  stocksplit_adj   div_adj
Date                                                                        
2008-08-26 00:00:00-03:00   0.024332           0.0             1.0  0.024332
2009-01-02 00:00:00-02:00   0.023102           0.0             1.0  0.023102
2009-05-04 00:00:00-03:00   0.020682           0.0             1.0  0.020682
2009-05-18 00:00:00-03:00   0.018644           0.0             1.0  0.018644
2009-08-17 00:00:00-03:00   0.020019           0.0             1.0  0.020019
...                              ...           ...             ...       ...
2023-09-29 00:00:00-03:00   0.105230           0.0             9.0  0.947070
2024-01-02 00:00:00-03:00   0.100519           0.0             9.0  0.904671
2024-02-28 00:00:00-03:00   0.066900           0.0             9.0  0.602100
2024-03-27 00:00:00-03:00   0.052453           0.0             9.0  0.472077
2024-06-19 00:00:00-03:00   0.086087           0.0             9.0  0.774783

[79 rows x 4 columns]

In [89]:
stock['year'] = stock.index.year
stock

Dividends  Stock Splits  stocksplit_adj   div_adj  \
Date                                                                           
2008-08-26 00:00:00-03:00   0.024332           0.0             1.0  0.024332   
2009-01-02 00:00:00-02:00   0.023102           0.0             1.0  0.023102   
2009-05-04 00:00:00-03:00   0.020682           0.0             1.0  0.020682   
2009-05-18 00:00:00-03:00   0.018644           0.0             1.0  0.018644   
2009-08-17 00:00:00-03:00   0.020019           0.0             1.0  0.020019   
...                              ...           ...             ...       ...   
2023-09-29 00:00:00-03:00   0.105230           0.0             9.0  0.947070   
2024-01-02 00:00:00-03:00   0.100519           0.0             9.0  0.904671   
2024-02-28 00:00:00-03:00   0.066900           0.0             9.0  0.602100   
2024-03-27 00:00:00-03:00   0.052453           0.0             9.0  0.472077   
2024-06-19 00:00:00-03:00   0.086087           0.0             9.0  0.774783   

                           year  
Date                             
2008-08-26 00:00:00-03:00  2008  
2009-01-02 00:00:00-02:00  2009  
2009-05-04 00:00:00-03:00  2009  
2009-05-18 00:00:00-03:00  2009  
2009-08-17 00:00:00-03:00  2009  
...                         ...  
2023-09-29 00:00:00-03:00  2023  
2024-01-02 00:00:00-03:00  2024  
2024-02-28 00:00:00-03:00  2024  
2024-03-27 00:00:00-03:00  2024  
2024-06-19 00:00:00-03:00  2024  

[79 rows x 5 columns]

In [90]:
stock_grp = stock.groupby(by=["year"]).sum()
stock_grp.tail(20)

Dividends  Stock Splits  stocksplit_adj   div_adj
year                                                   
2008   0.024332           0.0             1.0  0.024332
2009   0.110237           0.0             6.0  0.110237
2010   0.156855           0.0             7.0  0.156855
2011   0.174123           0.0             5.0  0.174123
2012   0.134854           0.0             4.0  0.134854
2013   0.164130           0.0             4.0  0.164130
2014   0.134735           0.0             4.0  0.134735
2015   0.266364           0.0             5.0  0.266364
2016   0.167857           0.0             4.0  0.167857
2017   0.150912           0.0             4.0  0.150912
2018   0.234043           0.0             4.0  0.234043
2019   0.268078           0.0             4.0  0.268078
2020   0.538440           0.0             4.0  0.538440
2021   0.977915           6.0            42.0  5.447611
2022   0.469106           0.0            45.0  4.221954
2023   0.487233           0.0            54.0  4.385097
2024   0.305959           0.0            36.0  2.753631

In [91]:
stock_grp["div_PCT_Change"] = stock_grp["div_adj"].pct_change(fill_method ='ffill')
stock_grp.tail(20)

/tmp/ipykernel_286499/2294672247.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  stock_grp["div_PCT_Change"] = stock_grp["div_adj"].pct_change(fill_method ='ffill')


Dividends  Stock Splits  stocksplit_adj   div_adj  div_PCT_Change
year                                                                   
2008   0.024332           0.0             1.0  0.024332             NaN
2009   0.110237           0.0             6.0  0.110237        3.530536
2010   0.156855           0.0             7.0  0.156855        0.422889
2011   0.174123           0.0             5.0  0.174123        0.110089
2012   0.134854           0.0             4.0  0.134854       -0.225524
2013   0.164130           0.0             4.0  0.164130        0.217094
2014   0.134735           0.0             4.0  0.134735       -0.179096
2015   0.266364           0.0             5.0  0.266364        0.976947
2016   0.167857           0.0             4.0  0.167857       -0.369821
2017   0.150912           0.0             4.0  0.150912       -0.100949
2018   0.234043           0.0             4.0  0.234043        0.550857
2019   0.268078           0.0             4.0  0.268078        0.145422
2020   0.538440           0.0             4.0  0.538440        1.008520
2021   0.977915           6.0            42.0  5.447611        9.117397
2022   0.469106           0.0            45.0  4.221954       -0.224990
2023   0.487233           0.0            54.0  4.385097        0.038642
2024   0.305959           0.0            36.0  2.753631       -0.372048

In [92]:
median_growth = stock_grp["div_PCT_Change"].median()
median_growth

np.float64(0.12775546537233062)

In [93]:
lst_Div = stock_grp.at[2021,'Dividends']
lst_Div

np.float64(0.977915)

In [94]:
exp_future_div = round(lst_Div * (1 + median_growth),2)
exp_future_div

np.float64(1.1)

In [95]:
# If you want to use the 10 year treasury yield today use this code
#bond = yf.Ticker("^TNX")
#hist = bond.history(period="today")
#risk_free_rate = round(hist.iloc[0]['Close']/100,4)
#risk_free_rate

In [96]:
risk_free_rate = 0.03

In [97]:
# assume the avg return for sp500 = 11%
mkt_return = .11

In [98]:
MKT_Risk_prem = mkt_return - risk_free_rate
MKT_Risk_prem

0.08

In [99]:
beta = ticker.info["beta"]
beta

0.59

In [100]:
COE = round(beta * MKT_Risk_prem + risk_free_rate,4)
COE

0.0772

In [101]:
fair_sharePrice = abs(round(exp_future_div/(COE-median_growth),2))
fair_sharePrice

np.float64(21.76)